Percona-Lab/pmm-api-tests

- inventory/agents_test.go
> PMM-3686 qan agent tests

- .gitignore
- .travis.yml
- Dockerfile
- Gopkg.lock
- Gopkg.toml
- Makefile
- vendor/github.com/jstemmer/go-junit-report/LICENSE
- vendor/github.com/jstemmer/go-junit-report/formatter/formatter.go
- vendor/github.com/jstemmer/go-junit-report/go-junit-report.go
- vendor/github.com/jstemmer/go-junit-report/parser/parser.go
Related to https://github.com/Percona-Lab/jenkins-pipelines/pull/206
> Added tests output converter to jUnit format for Jenkins.

- Dockerfile
- Makefile
> PMM-4448 Run tests with race detector by default.

- management/mysql_test.go
We still need to add new tests.
> PMM-4544 Remove old test.

- inventory/agents_mysqld_exporter_test.go
Updated the MySQLService Add method to update the tables count after the
connection checker is being called.
> PMM-5026 Added test for tables count

- helpers.go
- inventory/agents_mongodb_exporter_test.go
- inventory/agents_mysqld_exporter_test.go
- inventory/agents_node_exporter_test.go
- inventory/agents_postgres_exporter_test.go
- inventory/agents_proxysql_exporter_test.go
- inventory/agents_rds_exporter_test.go
- inventory/agents_test.go
- inventory/helpers.go
- inventory/nodes_test.go
- inventory/services_test.go
- management/mongodb_test.go
- management/mysql_test.go
- management/postgresql_test.go
- management/proxysql_test.go
- server/settings_test.go
After https://github.com/percona/pmm-managed/pull/315
> PMM-5008 Tests for node type validation.

- Gopkg.lock
- Gopkg.toml
- inventory/services_test.go
- management/mysql_test.go
- vendor/github.com/percona/pmm/api/inventorypb/json/client/agents/add_rds_exporter_responses.go
- vendor/github.com/percona/pmm/api/inventorypb/json/client/agents/change_rds_exporter_responses.go
- vendor/github.com/percona/pmm/api/inventorypb/json/client/agents/get_agent_responses.go
- vendor/github.com/percona/pmm/api/inventorypb/json/client/agents/list_agents_responses.go
- vendor/github.com/percona/pmm/api/inventorypb/json/client/services/add_my_sql_service_responses.go
- vendor/github.com/percona/pmm/api/inventorypb/json/client/services/get_service_responses.go
- vendor/github.com/percona/pmm/api/inventorypb/json/client/services/list_services_responses.go
- vendor/github.com/percona/pmm/api/managementpb/json/client/my_sql/add_my_sql_responses.go
- vendor/github.com/percona/pmm/api/managementpb/json/client/rds/add_rds_responses.go
https://jira.percona.com/browse/PMM-5042
Deps:
- https://github.com/percona/pmm/pull/506
- https://github.com/percona/pmm-managed/pull/363
FB: 
- https://github.com/Percona-Lab/pmm-submodules/pull/764
> PMM-5042 Add service address and socket test.

- .travis.yml
- Dockerfile
https://jira.percona.com/browse/PMM-6213
> PMM-6213 Remove go 1.13 from travis.

- server/auth_test.go
- server/readyz_test.go
https://github.com/percona/pmm-managed/pull/473
https://github.com/Percona-Lab/pmm-submodules/pull/1140
> PMM-4597 Fix API tests.

- server/logs_test.go
replaces https://github.com/Percona-Lab/pmm-api-tests/pull/133 
submodules PR https://github.com/Percona-Lab/pmm-submodules/pull/1183
> PMM-6401 fixes tests after replacing prometheus with victoriametrics

- management/dbaas/kubernetes_server_test.go
- management/dbaas/psmdb_cluster_test.go
- management/dbaas/xtra_db_cluster_test.go
- server/logs_test.go
https://jira.percona.com/browse/PMM-7025
FB: https://github.com/Percona-Lab/pmm-submodules/pull/1254
> Fix api tests

- management/ia/notifications_test.go
PMM-6968
FB: https://github.com/Percona-Lab/pmm-submodules/pull/1269
> PMM-6968 Improve channels tests

- management/ia/rules_test.go
* https://github.com/percona/pmm-managed/pull/588
* https://github.com/Percona-Lab/pmm-api-tests/pull/157
* https://github.com/Percona-Lab/pmm-submodules/pull/1331
> PMM-7207 Toggle Rule API test

- management/ia/rules_test.go
[PMM-7212](https://jira.percona.com/browse/PMM-7212)
> PMM-7212 Add test for creating rule from built-in template

- server/helpers.go
[PMM-6891](https://jira.percona.com/browse/PMM-6891)
> PMM-6891 Fix restore settings defaults

- Gopkg.lock
- management/ia/rules_test.go
- vendor/github.com/percona-platform/saas/pkg/common/severity.go
- vendor/github.com/percona/pmm/api/managementpb/ia/json/client/alerts/list_alerts_responses.go
- vendor/github.com/percona/pmm/api/managementpb/ia/json/client/rules/create_alert_rule_responses.go
- vendor/github.com/percona/pmm/api/managementpb/ia/json/client/rules/list_alert_rules_responses.go
https://github.com/percona/pmm-managed/pull/604
https://github.com/Percona-Lab/pmm-submodules/pull/1357
> PMM-7228 Fix severities and rule toggling

- management/ia/templates_test.go
[PMM-6941](https://jira.percona.com/browse/PMM-6941)
> PMM-6941 Update tests

- .travis.yml
- Dockerfile
- server/settings_test.go
No FB, but I tested it locally
> Fix tests for Go 1.15

- management/helpers.go
- management/mongodb_test.go
- management/mysql_test.go
- management/postgresql_test.go
- management/proxysql_test.go
[PMM-7145](https://jira.percona.com/browse/PMM-7145)
Build: https://github.com/Percona-Lab/pmm-submodules/pull/1428
> PMM-7145 Set PushMetricsEnabled flag

- management/helpers.go
- management/mongodb_test.go
- management/mysql_test.go
- management/postgresql_test.go
- management/proxysql_test.go
> PMM-7145 Set PushMetricsEnabled flag (#174)

- management/ia/rules_test.go
[PMM-7467](https://jira.percona.com/browse/PMM-7467)
> PMM-7467 Test IA rule expression

- server/auth_test.go
https://jira.percona.com/browse/PMM-6766
> PMM-6766: Remove QAN from tests

- Gopkg.lock
- Gopkg.toml
- management/haproxy_test.go
- vendor/github.com/percona/pmm/api/managementpb/json/client/ha_proxy/add_ha_proxy_responses.go
FB Percona-Lab/pmm-submodules#1514
> PMM-7487 HAProxy connection check.

- Gopkg.lock
- Gopkg.toml
- management/backup/locations_test.go
- vendor/github.com/percona/pmm/api/managementpb/backup/json/client/locations/add_location_responses.go
- vendor/github.com/percona/pmm/api/managementpb/backup/json/client/locations/change_location_responses.go
- vendor/github.com/percona/pmm/api/managementpb/backup/json/client/locations/list_locations_responses.go
Task: https://jira.percona.com/browse/PMM-7557
API: https://github.com/percona/pmm/pull/691
pmm-managed https://github.com/percona/pmm-managed/pull/677
FB: https://github.com/Percona-Lab/pmm-submodules/pull/1546
> PMM-7557: Add backup bucket field

- go.mod
- go.sum
- server/platform_auth_test.go
https://jira.percona.com/browse/SAAS-487
https://github.com/percona-platform/platform/pull/206
https://github.com/percona-platform/api-tests/pull/58
https://github.com/percona-platform/saas/pull/35
https://github.com/percona/pmm-managed/pull/694
https://github.com/Percona-Lab/pmm-api-tests/pull/205
https://github.com/percona-platform/authed/pull/91
> SAAS-487 Update API tests for new registration flow

- go.mod
- go.sum
- management/dbaas/kubernetes_server_test.go
API for disk is done in dbaas-controller, add basic tests for it.
> PMM-7652 DBaaS: Resource calculator - add stograge test

- go.mod
- go.sum
- server/checks_test.go
- server/helpers.go
https://github.com/percona/pmm/pull/714
https://github.com/Percona-Lab/pmm-submodules/pull/1644
https://github.com/percona/pmm-managed/pull/712
> PMM-7338 API test for change check interval

- inventory/services_test.go
https://github.com/Percona-Lab/pmm-submodules/pull/1673
> Fix external exporter tests

- management/backup/locations_test.go
[PMM-7832](https://jira.percona.com/browse/PMM-7832)
- managed - https://github.com/percona/pmm-managed/pull/728
---
> PMM-7832 skip test for s3 config

- inventory/services_test.go
https://jira.percona.com/browse/PMM-8013
pmm-managed PR: https://github.com/percona/pmm-managed/pull/748
FB: https://github.com/Percona-Lab/pmm-submodules/pull/1804
> PMM-8013: Fix test

- go.sum
- management/ia/channels_test.go
- management/ia/rules_test.go
- management/rds_test.go
- server/helpers.go
[PMM-2168](https://jira.percona.com/browse/PMM-2168)
> PMM-2168 disable rds exporter

- inventory/agents_test.go
[PMM-5016](https://jira.percona.com/browse/PMM-5016)
> PMM-5016 Enforce relationships between agents and services/nodes 
